### ISSUE TITLE
GetDesc() is not working as intended.

### ISSUE THREAD

**Issue by enescaglayan** [HypheX/roblox-trello#7]
![Screenshot_1](https://user-images.githubusercontent.com/47847977/62542191-f8fb4280-b863-11e9-93be-eeda7f7f70ef.png)
I get the kick message above if theres a description of my ban using this script:

`local Trello = require(script.Trello.Main)
local MainBoard = Trello:GetBoardByName("MyGameBanList")
local Banned = MainBoard:GetListByName('Banned')

function checkBanned(Player)
	local isBanned = Banned:GetCardByName(tostring(Player.Name))
	if isBanned then
		local reason = isBanned:GetDesc()
        if reason == nil or reason == "" then
        Player:Kick("You have been banned from this game. No reason written.")
        else
        Player:Kick("You have been banned from this game. Reason:"..reason)
        end
	end
end

-- Check for players yet to come
game:GetService('Players').PlayerAdded:Connect(checkBanned)

-- Check for players that already arrived
for _,p in pairs(game:GetService('Players'):GetPlayers()) do
	checkBanned(p)
end

while true do
	wait("25")
	for _,pp in pairs(game:GetService('Players'):GetPlayers()) do
	checkBanned(pp)
    end
end

print("All set!")`

**Comment by HypheX** [comment]
After analyzing your code, it appears that the problem does not originate on the API, but rather, in the Kick() method. 

This is because the kick message in the screenshot does not even show a kick reason, despite the fact that your script does include it.

**Comment by enescaglayan** [comment]
When i delete my self from banned list i dont get kicked but when i add my self to list without a reason
kick message is this: You have been banned from this game. No reason written.
but when i add a description it gives the kick message you saw in screen shot

**Comment by AlertShamrock** [comment]
Use elseif not reason == nil or reason == "" then kick("kick message"..reason)

**Comment by 23brewert** [comment]
Fixed

**Comment by HypheX** [comment]
Closing issue as this has been fixed.
